require("options")
require('quick-fix').setup()
require("neovide")
require("tab-management")
require("lazy-plugins")
require("sidebar")
require("custom-color-scheme").colorscheme()
vim.keymap.set("n", "<C-j>", "<C-w>j")
